server:
  port: 8103
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
spring:
  application:
    name: provider