server:
  port: 8301
spring:
  application:
    name: gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
zuul:
  routes:
    provider: /**
  prefix: /item #前面一定要加/
  strip-prefix: true


