server:
  port: 8401
spring:
  application:
    name: config
  profiles:
    active: env
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangdongjava/properties-demo.git
          default-label: master
